test_job:
  stage: test
  image: golang:1.23.4 # e.g., golang:1.23.4
  services:
    - name: rabbitmq:3.9-management-alpine # Use a specific version and management plugin
      alias: rabbitmq # Alias for easy access in your application/tests
  variables:
    RABBITMQ_HOST: "rabbitmq"
    RABBITMQ_USERNAME: "guest"
    RABBITMQ_PASSWORD: "guest"
    RABBITMQ_PORT: "5672" # Default RabbitMQ port
  script:
    - go mod tidy
    - go test ./...
